import { NextRequest } from 'next/server'
import { requireProjectOwner } from '@/lib/auth/guards'
import { createClient } from '@/lib/supabase/server'
import { errorResponse, handleApiError } from '@/lib/utils/api-response'
import { escapeHtml as _escapeHtmlBase } from '@/lib/utils/html'

interface RouteContext {
  params: Promise<{ id: string }>
}

// GET: 린 캔버스 PDF 데이터 생성 (HTML → 클라이언트에서 PDF 변환)
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params
    await requireProjectOwner(id)

    const supabase = await createClient()

    const { data: project } = await supabase
      .from('bi_projects')
      .select('name')
      .eq('id', id)
      .single()

    const { data: ideaCard, error: ideaError } = await supabase
      .from('bi_idea_cards')
      .select('problem, solution, target, differentiation, uvp, channels, revenue_streams, cost_structure, key_metrics')
      .eq('project_id', id)
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (ideaError || !ideaCard) {
      return errorResponse('아이디어를 찾을 수 없습니다.', 404)
    }

    const projectName = project?.name || 'Untitled Project'
    const date = new Date().toISOString().split('T')[0]

    const html = `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>Lean Canvas - ${projectName}</title>
<style>
  @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Pretendard', sans-serif; background: white; padding: 24px; }
  .header { text-align: center; margin-bottom: 24px; }
  .header h1 { font-size: 20px; font-weight: 700; color: #1e293b; }
  .header p { font-size: 12px; color: #64748b; margin-top: 4px; }
  .canvas { display: grid; grid-template-columns: repeat(5, 1fr); border: 2px solid #334155; border-radius: 8px; overflow: hidden; }
  .block { border: 1px solid #cbd5e1; padding: 12px; min-height: 120px; }
  .block h3 { font-size: 10px; font-weight: 700; color: #334155; text-transform: uppercase; margin-bottom: 6px; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
  .block p { font-size: 9px; color: #475569; line-height: 1.5; white-space: pre-wrap; }
  .block.tall { grid-row: span 2; min-height: 240px; }
  .block.wide { grid-column: span 5; min-height: 80px; }
  .block.half-wide { grid-column: span 5; min-height: 80px; }
  .bottom-row { display: grid; grid-template-columns: 1fr 1fr; grid-column: span 5; }
  .bottom-row .block { min-height: 80px; }
  .footer { text-align: center; margin-top: 16px; font-size: 10px; color: #94a3b8; }
  @media print { body { padding: 12px; } }
</style>
</head>
<body>
<div class="header">
  <h1>${projectName} - Lean Canvas</h1>
  <p>Generated by CASA AI Platform | ${date}</p>
</div>
<div class="canvas">
  <div class="block tall" style="background:#fef2f2">
    <h3>1. Problem</h3>
    <p>${escapeHtml(ideaCard.problem || '-')}</p>
  </div>
  <div class="block" style="background:#f0fdf4">
    <h3>4. Solution</h3>
    <p>${escapeHtml(ideaCard.solution || '-')}</p>
  </div>
  <div class="block tall" style="background:#fffbeb">
    <h3>3. UVP</h3>
    <p>${escapeHtml(ideaCard.uvp || '-')}</p>
  </div>
  <div class="block" style="background:#faf5ff">
    <h3>9. Unfair Advantage</h3>
    <p>${escapeHtml(ideaCard.differentiation || '-')}</p>
  </div>
  <div class="block tall" style="background:#fff1f2">
    <h3>2. Customer Segments</h3>
    <p>${escapeHtml(ideaCard.target || '-')}</p>
  </div>
  <div class="block" style="background:#eff6ff">
    <h3>8. Key Metrics</h3>
    <p>${escapeHtml(ideaCard.key_metrics || '-')}</p>
  </div>
  <div class="block" style="background:#ecfeff">
    <h3>5. Channels</h3>
    <p>${escapeHtml(ideaCard.channels || '-')}</p>
  </div>
  <div class="bottom-row">
    <div class="block" style="background:#f8fafc">
      <h3>7. Cost Structure</h3>
      <p>${escapeHtml(ideaCard.cost_structure || '-')}</p>
    </div>
    <div class="block" style="background:#f8fafc">
      <h3>6. Revenue Streams</h3>
      <p>${escapeHtml(ideaCard.revenue_streams || '-')}</p>
    </div>
  </div>
</div>
<div class="footer">Powered by CASA - CBNU AI-Agentic Startup Accelerator</div>
</body>
</html>`

    return new Response(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
      },
    })
  } catch (error) {
    return handleApiError(error)
  }
}

function escapeHtml(text: string): string {
  return _escapeHtmlBase(text, { nl2br: true })
}
